### ISSUE TITLE
Style the svg directly

### ISSUE THREAD

**Issue by luandro** [matthewwithanm/react-inlinesvg#20]
How can I give the loaded svg some style attributes such as width and height? It seems there's no way to access the svg at all.

**Comment by tnrich** [comment]
+1, it would be nice to know how to do this

**Comment by gilbarbara** [comment]
hey,
You can style it with css.
```css
.isvg {
  svg { 
    height: auto;
    width: 20rem;
 }
}
```
Don't forget to add a viewBox in your SVGs.
